FROM ubuntu:latest
RUN apt-get update -y
COPY barginerFish /usr/local/bin/exe/barginerFish
COPY templates /usr/local/bin/exe/templates
COPY static /usr/local/bin/exe/static
COPY db /usr/local/bin/exe/db
RUN chmod +x /usr/local/bin/exe/barginerFish
ENTRYPOINT ["/usr/local/bin/exe/barginerFish"]