services:
  taroly:
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_traefik"
      - "traefik.http.routers.to-fish.rule=Host(`<SUBDOMAIN>.<DOMAIN>`)" # Replace <SUBDOMAIN> and <DOMAIN> with your domain
      - "traefik.http.routers.to-fish.entrypoints=websecure"
      - "traefik.http.routers.to-fish.tls=true"
      - "traefik.http.routers.to-fish.tls.certresolver=myresolver" # Replace myresolver with your certresolver
      - "traefik.http.services.http-fish.loadbalancer.server.port=80"

      - "traefik.http.middlewares.cors-headers.headers.accessControlAllowOriginList=*"
      - "traefik.http.middlewares.cors-headers.headers.accessControlAllowHeaders=Origin, X-Requested-With, Content-Type, Accept, Authorization"
      - "traefik.http.middlewares.cors-headers.headers.accessControlAllowMethods=GET, POST, PUT, DELETE, OPTIONS"
