services:
  web:
    image: nekogawa/fish
    restart: unless-stopped
    volumes:
      - ./db:/usr/local/bin/exe/db
      - ./images:/usr/local/bin/exe/static/images
    networks:
      traefik_traefik:

networks:
  traefik_traefik:
    external: true